### ISSUE TITLE
Exception in thread "Task submitter" java.lang.NumberFormatException: For input string: "null"

### ISSUE THREAD

**Issue by EnHu359** [bzhanglab/neoflow#4]
I tried to use neoflow by exampledata.But I get an error when I run neoflow_msms.nf
this is my code
`
./nextflow run ./neoflow-master/neoflow_msms.nf  \
--ms /mnt/g/example_data/mgf  \
--msms_para_file /mnt/g/example_data/comet_parameter.txt \
--search_engine comet 
--db ./test/customized_database/neoflow_crc_target_decoy.fasta
--out_dir test2 \
--pv_refdb ./test/customized_database/ref.fasta 
--pv_tol 20 
--pv_itol 0.05
`

**then I get the following erros:**

`
N E X T F L O W  ~  version 21.10.6
Launching `./neoflow-master/neoflow_msms.nf` [reverent_watson] - revision: 9f41504eb3
Process multiple MS/MS files.
[-        ] process > msms_searching          -
[-        ] process > calculate_fdr           -
[-        ] process > prepare_pepquery_input  -
[-        ] process > run_pepquery            -
[-        ] process > add_pepquery_validation -
WARN: Access to undefined parameter `cpu` -- Initialise it to a default value eg. `params.cpu = some_value`
Error executing process > 'msms_searching (spec-00565.mgf)'

Caused by:
  For input string: "null"

Exception in thread "Task submitter" java.lang.NumberFormatException: For input string: "null"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at org.codehaus.groovy.runtime.StringGroovyMethods.toInteger(StringGroovyMethods.java:3134)
        at org.codehaus.groovy.runtime.StringGroovyMethods.asType(StringGroovyMethods.java:192)
        at nextflow.extension.Bolts.asType(Bolts.groovy:449)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.metaclass.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:54)
        at org.codehaus.groovy.runtime.metaclass.NewInstanceMetaMethod.invoke(NewInstanceMetaMethod.java:54)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePojoMethod(InvokerHelper.java:1017)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1008)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:180)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.asType(ScriptBytecodeAdapter.java:603)
        at nextflow.processor.TaskConfig.getCpus(TaskConfig.groovy:282)
        at nextflow.processor.TaskConfig$getCpus$18.call(Unknown Source)
        at nextflow.processor.TaskHandler.getTraceRecord(TaskHandler.groovy:168)
        at nextflow.executor.LocalTaskHandler.super$2$getTraceRecord(LocalExecutor.groovy)
        at sun.reflect.GeneratedMethodAccessor336.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:164)
        at nextflow.executor.LocalTaskHandler.getTraceRecord(LocalExecutor.groovy:256)
        at nextflow.Session.notifyTaskComplete(Session.groovy:972)
        at nextflow.processor.TaskPollingMonitor.submitPendingTasks(TaskPollingMonitor.groovy:566)
        at nextflow.processor.TaskPollingMonitor.submitLoop(TaskPollingMonitor.groovy:387)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[-        ] process > msms_searching          -
[-        ] process > calculate_fdr           -
[-        ] process > prepare_pepquery_input  -
[-        ] process > run_pepquery            -
[-        ] process > add_pepquery_validation -
WARN: Access to undefined parameter `cpu` -- Initialise it to a default value eg. `params.cpu = some_value`
Error executing process > 'msms_searching (spec-00565.mgf)'

Caused by:
  For input string: "null"
`
Is there some one can help me? thank you very much!

**Comment by WLYYYYY** [comment]
Hello @wenbostar, sorry to tag you directly, 
but I got the same error almost one year after this issue was created: 
<img width="659" alt="neoflow_error_module_2" src="https://user-images.githubusercontent.com/93225433/222812336-4521b79a-bab7-4780-ba3a-c4b594990219.png">

It would be very much appreaciated if you could provide some comment!

**Comment by Sawakotx** [comment]
> Hello @wenbostar, sorry to tag you directly, but I got the same error almost one year after this issue was created: <img alt="neoflow_error_module_2" width="659" src="https://user-images.githubusercontent.com/93225433/222812336-4521b79a-bab7-4780-ba3a-c4b594990219.png">
> 
> It would be very much appreaciated if you could provide some comment!

Hello~ @WLYYYYY, I successed this step this morning. 
I add a line 'params.cpu = 0 ' in the neoflow_msms.nf,  which looks like the code I show in the image below.
![image](https://github.com/bzhanglab/neoflow/assets/82040209/51120049-b672-4b79-8f76-0a4899ff5823)

Wish this solution will help you!
